name: Check workflows
on:
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@v3
      - name: Check workflows pinned
        uses: neutrinos-os/action-ratchet-check-dir@a6d0f892d9232128e0cda69a14c4bbe94dbbafaa
